@startuml
'https://plantuml.com/class-diagram

class AlternatingOrderFactoryFactory
class BuilderForOneElement
class BuilderForOneElementContainer
class List<AlternatingOrderElement>
class SyncAction
abstract class LockVisitor
abstract class AlternatingOrderElement
abstract class SyncActionFromRun

@enduml