@startuml
'https://plantuml.com/class-diagram


package interleave {
}

note bottom of interleave
Parent package. Access to all other packages except syncAction
parent to child for interleave is
reverse to syncActionAndBlock
end note

package syncActionAndBlock {
}

package block {
}

package syncAction {
}

package alternatingOrder   {
}

interleave --> block
block --> syncActionAndBlock : implements
syncAction --> syncActionAndBlock : implements
syncActionAndBlock --> alternatingOrder

@enduml