package com.anarsoft.race.detection.process

import com.anarsoft.race.detection.process.directMemory.ContextReadDirectMemory
import com.anarsoft.race.detection.process.syncAction.ContextProcessSyncAction
import com.anarsoft.race.detection.process.monitor.ContextMonitor
import com.anarsoft.race.detection.process.field.ContextFieldIdMap
import com.anarsoft.race.detection.process.aggregate.ContextBuildAggregate
import com.anarsoft.race.detection.process.setStacktraceOrdinal.ContextSetStacktraceOrdinal
import com.anarsoft.race.detection.process.monitorRelation.ContextCreateMonitorRelation
import com.anarsoft.race.detection.process.detectDeadlocks.ContextDetectDeadlocks
import com.anarsoft.race.detection.process.aggregate.ContextBuildMethodOrdinalAggregate
import com.anarsoft.race.detection.process.setMonitorInfo.ContextSetMonitorInfo
import com.anarsoft.race.detection.process.arrayId.ContextSetArrayOrdinal
import com.anarsoft.race.detection.process.nonVolatileField.ArrayAccessEvent

trait ContextReadAndProzessSyncActionAndMonitorEvents 
extends ContextReadDirectMemory 
with ContextProcessSyncAction
with ContextFieldIdMap
with ContextBuildAggregate
with ContextSetStacktraceOrdinal
with ContextCreateMonitorRelation
with ContextDetectDeadlocks
with ContextBuildMethodOrdinalAggregate
with ContextSetMonitorInfo
with ContextSetArrayOrdinal[ArrayAccessEvent]
{
  def arrayIdEventList = arrayAccessEventList;
}