@startuml
'https://plantuml.com/class-diagram

class KeyToOperation


KeyToOperation -> DependentOperationAndPositionOrContainer

DependentOperationAndPositionOrContainer <|-- DependentOperationAndPosition

DependentOperationAndPositionOrContainer <|-- LockOrConditionContainer

DependentOperationAndPosition --> DependentOperation


DependentOperation <|-- BarrierOperation

DependentOperation <|-- VolatileOperation

@enduml